import { ArrowLeft, CheckCircle2, Clock3, Copy, Database, Download, FileText, RefreshCw, Router, Wifi } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { DownloadModal } from '../components/DownloadModal'
import { MetricCard } from '../components/MetricCard'
import { StatusBadge } from '../components/StatusBadge'
import { TelemetryChart } from '../components/TelemetryChart'
import { devices as mockDevices } from '../mocks/data'
import { useDeviceFiles, useDevices, useTelemetry } from '../hooks/useData'
import type { DeviceFile, RangeKey } from '../types'
import { formatDateTime, formatFileSize, formatRelative, getDeviceState, rssiQuality } from '../utils'

export function DevicePage() {
  const { code } = useParams(); const {data:devices}=useDevices(); const device = devices.find(d=>d.code===code) ?? mockDevices.find(d=>d.code===code) ?? mockDevices[0]; const [range,setRange]=useState<RangeKey>('24h'); const [download,setDownload]=useState<DeviceFile|null>(null)
  const {data:telemetry}=useTelemetry(device,range); const {data:files,reload:reloadFiles,loading:filesLoading}=useDeviceFiles(device); const state=getDeviceState(device.lastSeen)
  return <div className="page"><Link className="back-link" to="/"><ArrowLeft size={16}/> All devices</Link><section className="device-hero"><div><div className="device-title-row"><span className="device-hero-icon"><Router/></span><div><span className="eyebrow">Environmental data logger</span><h1>{device.code} <em>·</em> {device.name}</h1></div></div><p>{device.location} <button className="copy-btn" aria-label="Copy device ID" onClick={()=>navigator.clipboard?.writeText(device.code)}><Copy size={13}/></button></p></div><div className="hero-status"><StatusBadge state={state}/><span><Clock3 size={14}/> Last contact {formatRelative(device.lastSeen)}</span></div></section>
    <section className="metrics"><MetricCard label="PM2.5" value={device.latest.pm25} unit="µg/m³" change={-1.2} tone="blue"/><MetricCard label="PM10" value={device.latest.pm10} unit="µg/m³" change={2.4} tone="purple"/><MetricCard label="Temperature" value={device.latest.temperature} unit="°C" change={.3} tone="amber"/><MetricCard label="Relative humidity" value={device.latest.rh} unit="%" change={-2} tone="teal"/></section>
    <section className="charts-section"><div className="section-head"><div><h2>Environmental telemetry</h2><p>Five-minute summary data · gaps indicate unavailable readings</p></div><div className="range-picker">{(['6h','24h','7d','30d'] as RangeKey[]).map(r=><button key={r} className={range===r?'active':''} onClick={()=>setRange(r)}>{r}</button>)}</div></div><div className="chart-grid"><TelemetryChart title="Fine particles · PM2.5" unit="µg/m³" data={telemetry} dataKey="pm25" color="#2571c6"/><TelemetryChart title="Particles · PM10" unit="µg/m³" data={telemetry} dataKey="pm10" color="#7657c8"/><TelemetryChart title="Temperature" unit="°C" data={telemetry} dataKey="temperature" color="#d27c26"/><TelemetryChart title="Relative humidity" unit="%" data={telemetry} dataKey="rh" color="#188c81"/></div></section>
    <section className="lower-grid"><article className="panel health-panel"><div className="panel-head"><div><span className="eyebrow">Diagnostics</span><h2>System health</h2></div><span className="health-score"><CheckCircle2 size={16}/> 5/5 checks</span></div><div className="health-list">{[['ESP32',state==='online','Cloud link'],['SPS30',device.health.sps30,'Particle sensor'],['SHT3x',device.health.sht3x,'Temperature + RH'],['RTC',device.health.rtc,'Clock synchronised'],['SD card',device.health.sd,'Recording normally']].map(([name,ok,desc])=><div key={String(name)}><span className={`check-dot ${ok?'ok':'bad'}`}>{ok?<CheckCircle2 size={15}/>:<span>!</span>}</span><span><strong>{name}</strong><small>{desc}</small></span><b>{ok?'Operational':'Check'}</b></div>)}</div><div className="health-meta"><div><Wifi/><span><small>Wi-Fi signal</small><strong>{device.rssi} dBm · {rssiQuality(device.rssi)}</strong></span></div><div><Database/><span><small>Active SD file</small><strong>{device.currentFilename}</strong></span></div><div><FileText/><span><small>Current size</small><strong>{formatFileSize(device.currentFileSize)}</strong></span></div></div></article>
      <article className="panel files-panel"><div className="panel-head"><div><span className="eyebrow">On-device storage</span><h2>Recent data files</h2></div><button className="button secondary" onClick={reloadFiles}><RefreshCw className={filesLoading?'spin':''} size={15}/> Refresh list</button></div><div className="file-table">{files.slice(0,4).map(file=><div className="file-row" key={file.id}><span className="file-icon"><FileText size={17}/></span><span className="file-name"><strong>{file.filename}</strong><small>{formatDateTime(file.modifiedAt)}</small></span><span className="file-size">{formatFileSize(file.size)}</span><button className="icon-btn" onClick={()=>setDownload(file)} aria-label={`Download ${file.filename}`}><Download size={17}/></button></div>)}</div><Link to="/files" className="text-link">View all files →</Link></article></section>
    <section className="architecture-note"><div><strong>Remote dashboard</strong><span>5-minute telemetry, device health and requested CSV transfers.</span></div><div><strong>Local dashboard</strong><span>Direct logger controls available when connected to the device network.</span></div><p>Independent by design—cloud availability never blocks scientific logging.</p></section>{download&&<DownloadModal file={download} deviceCode={device.code} deviceId={device.id} onClose={()=>setDownload(null)}/>}</div>
}
