import { ArrowRight, ArrowUpRight, Clock3, Filter, RadioTower, Search, Wifi } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { StatusBadge } from '../components/StatusBadge'
import { useDevices } from '../hooks/useData'
import { formatRelative, getDeviceState, rssiQuality } from '../utils'

export function FleetPage() {
  const {data:devices,loading,error,reload}=useDevices()
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all'|'online'|'attention'>('all')
  const filtered = useMemo(() => devices.filter(d => (d.code+d.name+d.location).toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'online' ? getDeviceState(d.lastSeen) === 'online' : getDeviceState(d.lastSeen) !== 'online'))), [devices, query, filter])
  const online = devices.filter(d => getDeviceState(d.lastSeen) === 'online').length
  return <div className="page"><section className="page-heading"><div><span className="eyebrow">Environmental monitoring network</span><h1>Fleet overview</h1><p>Live operational state and latest five-minute summaries from every field logger.</p></div><button className="last-updated refresh-plain" onClick={reload}><span className="live-pulse"/><div><small>{loading?'Refreshing':'Last updated'}</small><strong>{loading?'Please wait…':'Just now'}</strong></div></button></section>
    {error&&<div className="error-banner">Could not refresh devices. {error} <button onClick={reload}>Retry</button></div>}
    <section className="summary-grid"><div className="summary-card feature"><div><span>Network availability</span><strong>{Math.round(online/devices.length*100)}<small>%</small></strong><p>{online} of {devices.length} loggers reporting normally</p></div><div className="availability-ring" style={{'--value': `${online/devices.length*360}deg`} as React.CSSProperties}><span>{online}/{devices.length}</span></div></div><div className="summary-card"><span>Online now</span><strong>{online}</strong><small className="positive"><ArrowUpRight size={14}/> Healthy</small></div><div className="summary-card"><span>Needs attention</span><strong>{devices.length-online}</strong><small>1 stale · 1 offline</small></div><div className="summary-card"><span>Telemetry today</span><strong>1,096</strong><small>99.2% delivery rate</small></div></section>
    <section className="section-head"><div><h2>Field loggers</h2><p>{filtered.length} devices shown</p></div><div className="controls"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search loggers..." aria-label="Search loggers"/></label><div className="filter-wrap"><Filter size={15}/><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)} aria-label="Filter devices"><option value="all">All devices</option><option value="online">Online</option><option value="attention">Needs attention</option></select></div></div></section>
    <section className="device-grid">{filtered.map(device => { const state = getDeviceState(device.lastSeen); return <article className="device-card" key={device.id}><div className="device-card-top"><div className="device-id"><span className="device-icon"><RadioTower size={19}/></span><div><span>{device.code}</span><h3>{device.name}</h3></div></div><StatusBadge state={state}/></div><p className="location">{device.location}</p><div className="device-readings"><div><small>PM2.5</small><strong>{device.latest.pm25?.toFixed(1)}</strong><span>µg/m³</span></div><div><small>PM10</small><strong>{device.latest.pm10?.toFixed(1)}</strong><span>µg/m³</span></div><div><small>Temp.</small><strong>{device.latest.temperature?.toFixed(1)}</strong><span>°C</span></div><div><small>Humidity</small><strong>{device.latest.rh?.toFixed(0)}</strong><span>%</span></div></div><div className="device-meta"><span><Wifi size={15}/><span>{device.rssi} dBm · {rssiQuality(device.rssi)}</span></span><span><Clock3 size={15}/><span>{formatRelative(device.lastSeen)}</span></span></div><Link className="device-link" to={`/device/${device.code}`}><span>Open dashboard</span><ArrowRight size={17}/></Link></article>})}</section>
    {!filtered.length && <div className="empty"><Search size={24}/><h3>No loggers found</h3><p>Try changing the search or status filter.</p></div>}
  </div>
}
