import { CheckCircle2, Download, FileText, LoaderCircle, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { demoMode, supabase } from '../services/supabase'
import type { DeviceFile, DownloadStatus } from '../types'
import { downloadLabel, formatFileSize } from '../utils'

export function DownloadModal({ file, deviceCode, deviceId, onClose }: { file: DeviceFile; deviceCode: string; deviceId: string; onClose: () => void }) {
  const [progress,setProgress]=useState(0); const [status,setStatus]=useState<DownloadStatus>('queued'); const [url,setUrl]=useState(''); const [error,setError]=useState('')
  useEffect(()=>{if(demoMode){const timer=window.setInterval(()=>setProgress(p=>{const next=p>=100?100:Math.min(100,p+Math.ceil(Math.random()*9));setStatus(next===100?'ready':next>8?'uploading':next>0?'device_acknowledged':'queued');return next}),650);return()=>clearInterval(timer)}if(!supabase)return;const client=supabase;let active=true;let poll=0;void(async()=>{const {data,error:requestError}=await client.functions.invoke('request-file-download',{body:{device_id:deviceId,filename:file.filename}});if(requestError||!data?.request_id){if(active)setError(requestError?.message??'Unable to create download request');return}const check=async()=>{const {data:row,error:pollError}=await client.from('download_requests').select('status,progress_percent,storage_path').eq('id',data.request_id).single();if(!active)return;if(pollError){setError(pollError.message);return}setStatus(row.status as DownloadStatus);setProgress(row.progress_percent);if(row.status==='ready'&&row.storage_path){const {data:signed}=await client.storage.from('temporary-downloads').createSignedUrl(row.storage_path,60);if(signed)setUrl(signed.signedUrl);window.clearInterval(poll)}};await check();poll=window.setInterval(()=>void check(),2000)})();return()=>{active=false;window.clearInterval(poll)}},[deviceId,file.filename])
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="download-title"><div className="modal"><button className="modal-close icon-btn" onClick={onClose} aria-label="Close"><X size={18}/></button><div className={`modal-icon ${status==='ready'?'success':''}`}>{status==='ready'?<CheckCircle2/>:<FileText/>}</div><span className="eyebrow">Secure temporary transfer</span><h2 id="download-title">{status==='ready'?'Your file is ready':'Retrieving data file'}</h2><p>{status==='ready'?'The temporary download is available for the next 15 minutes.':'The logger streams this file directly from its SD card.'}</p><div className="file-summary"><div><small>Device</small><strong>{deviceCode}</strong></div><div><small>File</small><strong>{file.filename}</strong></div><div><small>Size</small><strong>{formatFileSize(file.size)}</strong></div></div><div className="progress-copy"><span>{status!=='ready'&&<LoaderCircle className="spin" size={15}/>} {downloadLabel[status]}</span><strong>{progress}%</strong></div><div className="progress"><span style={{width:`${progress}%`}}/></div>{error&&<div className="auth-error" role="alert">{error}</div>}{status==='ready'?<a className={`button primary full ${url?'':'disabled'}`} href={url||undefined} download><Download size={17}/> {url?'Download CSV':'Preparing secure link...'}</a>:<button className="button secondary full" onClick={onClose}>Close window</button>}<div className="security-note">Encrypted in transit · Auto-deleted after expiry</div></div></div>
}
